# Generated by Django 5.0.3 on 2024-03-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task4", "0002_alter_standings_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name="coach",
            name="number_of_titles_won",
        ),
        migrations.AlterField(
            model_name="coach",
            name="age",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name="coach",
            name="titles_won",
            field=models.ManyToManyField(related_name="title_coach", to="task4.title"),
        ),
    ]
