# Generated by Django 5.0.3 on 2024-03-31 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task4", "0003_title_remove_coach_number_of_titles_won_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfermarket",
            name="from_club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_out",
                to="task4.team",
            ),
        ),
        migrations.AlterField(
            model_name="transfermarket",
            name="to_club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_in",
                to="task4.team",
            ),
        ),
    ]
