# Generated by Django 5.0.3 on 2024-03-31 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task4", "0004_alter_transfermarket_from_club_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="championship",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="championship_name",
                to="task4.championship",
            ),
            preserve_default=False,
        ),
    ]
